spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

datasource:
  master:
    jdbc-url: jdbc:mysql://lc0:3306/daenerys?useSSL=false
    username: test
    password: test
  slave:
    jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
server:
  port: 8099
