spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        # 数据库驱动类名
        type: com.zaxxer.hikari.HikariDataSource
        drivercClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://lc0:3306/daenerys?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: test
        password: test
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        drivercClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: ds1
      slave-data-source-names: ds0
    props:
      sql:
        show: true
    enabled: true


datasource:
  master:
    jdbc-url: jdbc:mysql://lc0:3306/daenerys?useSSL=false
    username: test
    password: test
  slave:
    jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
server:
  port: 8099


hasSharding: false

datasource:
  d0:
    jdbc-url: jdbc:mysql://localhost:3306/d0?useSSL=false
    username: root
    password: root
  d1:
    jdbc-url: jdbc:mysql://localhost:3306/d1?useSSL=false
    username: root
    password: root
  singleton:
    jdbc-url: jdbc:mysql://localhost:3306/singleton?useSSL=false
    username: root
    password: root